# Open the pickle and the files

In [1]:
import numpy as np
import pickle

In [5]:
X_test=np.loadtxt('X_test.csv', delimiter=',')
y_test=np.loadtxt('y_test.csv', delimiter=',')

In [9]:
best_model_ever=pickle.load(open('mymodel.sav', 'rb'))

In [11]:
best_model_ever['model'].best_score_

0.9285714285714286

In [12]:
best_model_ever['pca'].explained_variance_ratio_

array([0.56156834, 0.11333084, 0.07462825, 0.06813563, 0.05732097])

In [ ]:
class model:
    
    def __init__(self, params):
        self.params=params
        
    def fit(self, X_train,y_train):
        self.X_train=X_train
        self.very_specific_parameter_epsilon=X_train*y_train*np.inverse(X_train*X_train.T)

In [13]:
best_model_ever.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
from sklearn.metrics import recall_score, confusion_matrix

In [15]:
recall_score(y_test, best_model_ever.predict(X_test))

0.8571428571428571

In [16]:
confusion_matrix(y_test, best_model_ever.predict(X_test))

array([[232,   4],
       [  2,  12]], dtype=int64)