<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy</a></span></li><li><span><a href="#Lambda-functions" data-toc-modified-id="Lambda-functions-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Lambda functions</a></span><ul class="toc-item"><li><span><a href="#Create-function-that-returns-a-function" data-toc-modified-id="Create-function-that-returns-a-function-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Create function that returns a function</a></span></li><li><span><a href="#Lambda-+-list-comprehensions" data-toc-modified-id="Lambda-+-list-comprehensions-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Lambda + list comprehensions</a></span></li><li><span><a href="#Another-example" data-toc-modified-id="Another-example-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Another example</a></span></li><li><span><a href="#Pros-and-cons" data-toc-modified-id="Pros-and-cons-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Pros and cons</a></span></li></ul></li><li><span><a href="#Map,-Filter,-Reduce" data-toc-modified-id="Map,-Filter,-Reduce-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Map, Filter, Reduce</a></span><ul class="toc-item"><li><span><a href="#Map" data-toc-modified-id="Map-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Map</a></span></li><li><span><a href="#Filter" data-toc-modified-id="Filter-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Filter</a></span></li><li><span><a href="#Reduce" data-toc-modified-id="Reduce-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Reduce</a></span></li></ul></li><li><span><a href="#MAAM---Map,-Apply,-ApplyMap" data-toc-modified-id="MAAM---Map,-Apply,-ApplyMap-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>MAAM - Map, Apply, ApplyMap</a></span><ul class="toc-item"><li><span><a href="#All-above-+-lambda" data-toc-modified-id="All-above-+-lambda-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>All above + lambda</a></span></li><li><span><a href="#Applymap" data-toc-modified-id="Applymap-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Applymap</a></span></li></ul></li></ul></div>

# Numpy

In [1]:
import numpy as np

In [2]:
a=np.random.random((2,2))

In [3]:
a

array([[0.79095648, 0.64071871],
       [0.64623784, 0.27803754]])

In [4]:
a[0,0]

0.7909564757210724

In [5]:
a[1,0]

0.6462378372495828

In [7]:
a.round(2)

array([[0.79, 0.64],
       [0.65, 0.28]])

In [8]:
a

array([[0.79095648, 0.64071871],
       [0.64623784, 0.27803754]])

In [9]:
a[0]

array([0.79095648, 0.64071871])

In [10]:
a[:,0]

array([0.79095648, 0.64623784])

In [17]:
b=np.random.random((4,3,2))

In [18]:
#three dimensional tensor
b

array([[[0.37551001, 0.44332445],
        [0.71309919, 0.02925933],
        [0.28956118, 0.33961164]],

       [[0.7103583 , 0.06581192],
        [0.883457  , 0.53113925],
        [0.24963492, 0.93275123]],

       [[0.25304886, 0.51298314],
        [0.74658382, 0.02009138],
        [0.83621613, 0.7772342 ]],

       [[0.62698917, 0.09317584],
        [0.65343018, 0.46256921],
        [0.25883577, 0.77272347]]])

In [19]:
b[3]

array([[0.62698917, 0.09317584],
       [0.65343018, 0.46256921],
       [0.25883577, 0.77272347]])

In [20]:
b[3,1]

array([0.65343018, 0.46256921])

In [21]:
b[:,1]

array([[0.71309919, 0.02925933],
       [0.883457  , 0.53113925],
       [0.74658382, 0.02009138],
       [0.65343018, 0.46256921]])

In [22]:
b[:,:,0]

array([[0.37551001, 0.71309919, 0.28956118],
       [0.7103583 , 0.883457  , 0.24963492],
       [0.25304886, 0.74658382, 0.83621613],
       [0.62698917, 0.65343018, 0.25883577]])

# Lambda functions

In [23]:
def square_function(x):
    return x*x

In [24]:
square_function(2)

4

```python
   
lambda argument: statement that you want to return
```

In [26]:
ssquare=lambda x: x*x

In [29]:
ssquare(2)

4

In [31]:
summator=lambda x,y: x+y

In [32]:
summator(2,3)

5

In [33]:
div = lambda x,y: x/y if y!=0 else 0

In [34]:
div(2,3)

0.6666666666666666

In [35]:
div(5,10)

0.5

In [36]:
div(2,0)

0

## Create function that returns a function

In [37]:
def generate_range(lower):
    return lambda upper: range(lower,upper)

In [38]:
range(10)

range(0, 10)

In [39]:
custom_range=generate_range(5)

In [40]:
custom_range(10)

range(5, 10)

In [41]:
custom_range(20)

range(5, 20)

In [42]:
s16=generate_range(-16)

In [43]:
s16(16)

range(-16, 16)

## Lambda + list comprehensions

In [44]:
ssquare=lambda x: x*x

In [45]:
[ssquare(i) for i in range(20)]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [46]:
topics=['Python','MySQL','Pandas','Web Scraping','Data Viz','Statistics','Machine Learning']

In [48]:
[i.lower().replace(' ','_') for i in topics]

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [49]:
[(lambda x: x.lower().replace(' ','_'))(i) for i in topics ]

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [54]:
list(map(lambda x: x.lower().replace(' ','_'), topics))

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [59]:
list(map(lambda x: x.lower(), topics))

['python',
 'mysql',
 'pandas',
 'web scraping',
 'data viz',
 'statistics',
 'machine learning']

## Another example

In [63]:
dct={i:len(i) for i in topics}

In [66]:
import operator
dict(sorted(dct.items(), key=operator.itemgetter(1), reverse=True))

{'Machine Learning': 16,
 'Web Scraping': 12,
 'Statistics': 10,
 'Data Viz': 8,
 'Python': 6,
 'Pandas': 6,
 'MySQL': 5}

In [67]:
dict(sorted(dct.items(), reverse=True, key=lambda x: x[1]))

{'Machine Learning': 16,
 'Web Scraping': 12,
 'Statistics': 10,
 'Data Viz': 8,
 'Python': 6,
 'Pandas': 6,
 'MySQL': 5}

In [70]:
[(lambda x: x[1])(i) for i in dct.items()]

[6, 5, 6, 12, 8, 10, 16]

In [75]:
[i[1] for i in dct.items()]

[6, 5, 6, 12, 8, 10, 16]

In [79]:
dict(sorted(dct.items(), reverse=True, key=lambda x: x[0][-1]))

{'Data Viz': 8,
 'Pandas': 6,
 'Statistics': 10,
 'Python': 6,
 'Web Scraping': 12,
 'Machine Learning': 16,
 'MySQL': 5}

## Pros and cons

Disadvantages:
1. Not every function can be written as lambda function.
2. Overcomplication in some cases.

Advantages:
1. Concise 
2. Short
3. Return automatically
4. Can be passed without a variable

# Map, Filter, Reduce

## Map

In [83]:
def func(x):
    return x%2==0

In [84]:
l=[10,11,13,17,18]

In [85]:
func(l)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [86]:
[func(i) for i in l]

[True, False, False, False, True]

In [87]:
list(map(func,l))

[True, False, False, False, True]

In [88]:
import pandas as pd
import numpy as np

In [89]:
df=pd.DataFrame([[1,2,3],[2,3,np.nan]])

In [90]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

In [92]:
def ff(x):
    return float(x)

In [93]:
df[0].map(ff)

0    1.0
1    2.0
Name: 0, dtype: float64

**IMPORTANT!**
`map()` only works with `pd.Series`

In [94]:
df.map(ff)

AttributeError: 'DataFrame' object has no attribute 'map'

In [96]:
df[1].map(lambda x: x**2)

0    4
1    9
Name: 1, dtype: int64

In [97]:
dct={1:'apple',2:'plum'}

In [98]:
dct

{1: 'apple', 2: 'plum'}

In [99]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

In [100]:
df[0]

0    1
1    2
Name: 0, dtype: int64

In [101]:
df[1].map(dct)

0    plum
1     NaN
Name: 1, dtype: object

In [102]:
df[1]

0    2
1    3
Name: 1, dtype: int64

## Filter

In [103]:
list(map(func,l))

[True, False, False, False, True]

In [104]:
l

[10, 11, 13, 17, 18]

In [105]:
list(filter(func,l))

[10, 18]

In [107]:
df.index=['mouse','cat']

In [108]:
df

0  1    2
mouse  1  2  3.0
cat    2  3  NaN

In [110]:
df.filter(like='ouse', axis=0)

0  1    2
mouse  1  2  3.0

In [111]:
df.filter(like='ou', axis=0)

0  1    2
mouse  1  2  3.0

In [112]:
df.filter(like='a', axis=0)

0  1   2
cat  2  3 NaN

In [113]:
df.loc[df.index.str.contains('ouse')]

0  1    2
mouse  1  2  3.0

In [114]:
df.filter(items=[0,2],axis=1)

0    2
mouse  1  3.0
cat    2  NaN

In [115]:
df.filter(items=[0,2])

0    2
mouse  1  3.0
cat    2  NaN

## Reduce

<img src='https://camo.githubusercontent.com/642b6b863e9ec8a7af3fb34a9a87249fe1612d13/68747470733a2f2f7777772e707974686f6e2d636f757273652e65752f696d616765732f7265647563655f6469616772616d2e706e67'>

In [116]:
def func(a,b): return a+b

In [117]:
from functools import reduce

In [118]:
l

[10, 11, 13, 17, 18]

In [119]:
reduce(func,l)

69

In [120]:
sum(l)

69

In [121]:
#select the biggest number out of 2
def func(a,b):
    return a if a>b else b

In [122]:
reduce(func,l)

18

In [123]:
l=[10, 21, 13, 17, 18]

In [124]:
reduce(func,l)

21

In [125]:
func(10,21)

21

In [126]:
func(21,13)

21

In [127]:
func(21, 17)

21

In [128]:
func(21, 18)

21

In [138]:
# really dumb function just for the sake of another example

def func(a,b):
    if (b%2==0) or ((a+b)>31):
        return a
    else:
        return b

In [139]:
func(10,21)

21

In [140]:
func(21,13)

21

In [141]:
reduce(func,l)

21

In [133]:
l

[10, 21, 13, 17, 18]

# MAAM - Map, Apply, ApplyMap

In [142]:
df=pd.read_csv('https://ironhack.school/asset-v1:IRONHACK+DAFT+201910_PAR+type@asset+block@IMDB-Movie-Data.csv')

In [143]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [144]:
df.shape

(1000, 12)

In [146]:
df.Rating.max()

9.0

In [147]:
df.Rating.min()

1.9

In [148]:
df.Rating/2

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [149]:
df.Rating.map(lambda x: x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [150]:
def column_range(x):
    """x is a pandas series"""
    return x.max()-x.min()

In [151]:
df.Rating.map(column_range)

AttributeError: 'float' object has no attribute 'max'

In [155]:
df[['Rating']].apply(column_range)

Rating    7.1
dtype: float64

In [160]:
df[['Rating','Runtime (Minutes)']].apply(column_range)

Rating                 7.1
Runtime (Minutes)    125.0
dtype: float64

In [156]:
df

Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
1                  124     7.0  485820              126.46       65.0  
2                  117     7.3  157606              138.12       62.0  
3                  108     7.2   60545              270.32       59.0  
4                  123     6.2  393727              325.02       40.0  
..                 ...     ...     ...                 ...        ...  
995                111     6.2   27585                 NaN       45.0  
996                 94     5.5   73152               17.54       46.0  
997                 98     6.2   70699               58.01       50.0  
998                 93     5.6    4881                 NaN       22.0  
999                 87     5.3   12435               19.64       11.0  

[1000 rows x 12 columns]

In [169]:
def column_range(x):
    """x is a pandas series"""
    return x.max()-x.min() if type(x[0]) in (int,float) else len(x)

In [170]:
df.apply(column_range)

Rank                      999.00
Title                    1000.00
Genre                    1000.00
Description              1000.00
Director                 1000.00
Actors                   1000.00
Year                       10.00
Runtime (Minutes)         125.00
Rating                      7.10
Votes                 1791855.00
Revenue (Millions)        936.63
Metascore                  89.00
dtype: float64

* Map  | applies the function provided to every value of Series
* Apply | applies the function provided to every value of Series or to every Serie in DataFrame

In [173]:
df.Rating.apply(lambda x:x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [174]:
df.Rating.map(lambda x:x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [175]:
df.map()

AttributeError: 'DataFrame' object has no attribute 'map'

In [176]:
def missing_col(x):
    return x.isna().sum()

In [177]:
df.apply(missing_col)

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [178]:
df.isna().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

## All above + lambda

In [183]:
#all the action movies
df[df['Genre'].str.lower().str.contains('action')].head()

Rank                    Title                       Genre  \
0      1  Guardians of the Galaxy     Action,Adventure,Sci-Fi   
4      5            Suicide Squad    Action,Adventure,Fantasy   
5      6           The Great Wall    Action,Adventure,Fantasy   
8      9       The Lost City of Z  Action,Adventure,Biography   
12    13                Rogue One     Action,Adventure,Sci-Fi   

                                          Description        Director  \
0   A group of intergalactic criminals are forced ...      James Gunn   
4   A secret government agency recruits some of th...      David Ayer   
5   European mercenaries searching for black powde...     Yimou Zhang   
8   A true-life drama, centering on British explor...      James Gray   
12  The Rebel Alliance makes a risky move to steal...  Gareth Edwards   

                                               Actors  Year  \
0   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
4   Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
5       Matt Damon, Tian Jing, Willem Dafoe, Andy Lau  2016   
8   Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12  Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   

    Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                 121     8.1  757074              333.13       76.0  
4                 123     6.2  393727              325.02       40.0  
5                 103     6.1   56036               45.13       42.0  
8                 141     7.1    7188                8.01       78.0  
12                133     7.9  323118              532.17       65.0

In [190]:
# I dont want to see action fantasy movies in my selection. 
df[df['Genre'].str.lower().str.contains('action')&(~df['Genre'].str.lower().str.contains('fantasy'))]

Rank                     Title                       Genre  \
0       1   Guardians of the Galaxy     Action,Adventure,Sci-Fi   
8       9        The Lost City of Z  Action,Adventure,Biography   
12     13                 Rogue One     Action,Adventure,Sci-Fi   
14     15                  Colossal         Action,Comedy,Drama   
17     18              Jason Bourne             Action,Thriller   
..    ...                       ...                         ...   
954   955                Death Race      Action,Sci-Fi,Thriller   
958   959            3 Days to Kill       Action,Drama,Thriller   
968   969                   Wrecker      Action,Horror,Thriller   
969   970           The Lone Ranger    Action,Adventure,Western   
993   994  Resident Evil: Afterlife     Action,Adventure,Horror   

                                           Description            Director  \
0    A group of intergalactic criminals are forced ...          James Gunn   
8    A true-life drama, centering on British explor...          James Gray   
12   The Rebel Alliance makes a risky move to steal...      Gareth Edwards   
14   Gloria is an out-of-work party girl forced to ...     Nacho Vigalondo   
17   The CIA's most dangerous former operative is d...     Paul Greengrass   
..                                                 ...                 ...   
954  Ex-con Jensen Ames is forced by the warden of ...  Paul W.S. Anderson   
958  A dying CIA agent trying to reconnect with his...                 McG   
968  Best friends Emily and Lesley go on a road tri...      Micheal Bafaro   
969  Native American warrior Tonto recounts the unt...      Gore Verbinski   
993  While still out to destroy the evil Umbrella C...  Paul W.S. Anderson   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
8    Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12   Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   
14   Anne Hathaway, Jason Sudeikis, Austin Stowell,...  2016   
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
..                                                 ...   ...   
954  Jason Statham, Joan Allen, Tyrese Gibson, Ian ...  2008   
958  Kevin Costner, Hailee Steinfeld, Connie Nielse...  2014   
968  Anna Hutchison, Andrea Whitburn, Jennifer Koen...  2015   
969  Johnny Depp, Armie Hammer, William Fichtner,To...  2013   
993  Milla Jovovich, Ali Larter, Wentworth Miller,K...  2010   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
8                  141     7.1    7188                8.01       78.0  
12                 133     7.9  323118              532.17       65.0  
14                 109     6.4    8612                2.87       70.0  
17                 123     6.7  150823              162.16       58.0  
..                 ...     ...     ...                 ...        ...  
954                105     6.4  173731               36.06       43.0  
958                117     6.2   73567               30.69       40.0  
968                 83     3.5    1210                 NaN       37.0  
969                150     6.5  190855               89.29        NaN  
993                 97     5.9  140900               60.13       37.0  

[263 rows x 12 columns]

I want to have a very specific selection of movies. I am a bit sploiled movie critique and I want to see the following:
1. It should be an Action movie
2. The max number of genres that movie represents is 2
3. I dont like Action Fantasy movies. So I will only accept Action with Thriller or Adventure.

['Action',  
 'Action, Adventure',  
 'Action, Thriller']

In [199]:
df[df.Genre.str.split(',').map(lambda x: len(x)<3)]; # number of genres
df[df['Genre'].str.lower().str.contains('action')]; #contains action

In [200]:
df[df['Genre'].str.lower().str.contains('action')&
   ((df['Genre'].str.lower().str.contains('thriller'))|
    (df['Genre'].str.lower().str.contains('adventure')))]


Rank                           Title                       Genre  \
0       1         Guardians of the Galaxy     Action,Adventure,Sci-Fi   
4       5                   Suicide Squad    Action,Adventure,Fantasy   
5       6                  The Great Wall    Action,Adventure,Fantasy   
8       9              The Lost City of Z  Action,Adventure,Biography   
12     13                       Rogue One     Action,Adventure,Sci-Fi   
..    ...                             ...                         ...   
958   959                  3 Days to Kill       Action,Drama,Thriller   
968   969                         Wrecker      Action,Horror,Thriller   
969   970                 The Lone Ranger    Action,Adventure,Western   
990   991  Underworld: Rise of the Lycans    Action,Adventure,Fantasy   
993   994        Resident Evil: Afterlife     Action,Adventure,Horror   

                                           Description            Director  \
0    A group of intergalactic criminals are forced ...          James Gunn   
4    A secret government agency recruits some of th...          David Ayer   
5    European mercenaries searching for black powde...         Yimou Zhang   
8    A true-life drama, centering on British explor...          James Gray   
12   The Rebel Alliance makes a risky move to steal...      Gareth Edwards   
..                                                 ...                 ...   
958  A dying CIA agent trying to reconnect with his...                 McG   
968  Best friends Emily and Lesley go on a road tri...      Micheal Bafaro   
969  Native American warrior Tonto recounts the unt...      Gore Verbinski   
990  An origins story centered on the centuries-old...  Patrick Tatopoulos   
993  While still out to destroy the evil Umbrella C...  Paul W.S. Anderson   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
5        Matt Damon, Tian Jing, Willem Dafoe, Andy Lau  2016   
8    Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12   Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   
..                                                 ...   ...   
958  Kevin Costner, Hailee Steinfeld, Connie Nielse...  2014   
968  Anna Hutchison, Andrea Whitburn, Jennifer Koen...  2015   
969  Johnny Depp, Armie Hammer, William Fichtner,To...  2013   
990  Rhona Mitra, Michael Sheen, Bill Nighy, Steven...  2009   
993  Milla Jovovich, Ali Larter, Wentworth Miller,K...  2010   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
4                  123     6.2  393727              325.02       40.0  
5                  103     6.1   56036               45.13       42.0  
8                  141     7.1    7188                8.01       78.0  
12                 133     7.9  323118              532.17       65.0  
..                 ...     ...     ...                 ...        ...  
958                117     6.2   73567               30.69       40.0  
968                 83     3.5    1210                 NaN       37.0  
969                150     6.5  190855               89.29        NaN  
990                 92     6.6  129708               45.80       44.0  
993                 97     5.9  140900               60.13       37.0  

[198 rows x 12 columns]

In [234]:
df[df.Genre.str.lower().str.split(',').map(lambda x: (set(x) - set(['action','thriller','adventure']))==set())] #contains only combinations of action, thriller and adventure

Rank                                          Title  \
17     18                                   Jason Bourne   
123   124                           Boyka: Undisputed IV   
124   125                          The Dark Knight Rises   
164   165                                  Casino Royale   
169   170                                        Spectre   
233   234             Mission: Impossible - Rogue Nation   
270   271                                        Skyfall   
282   283                                    Death Proof   
284   285                                       Hercules   
289   290                                           Iris   
344   345                                   Spider-Man 3   
368   369                         The Amazing Spider-Man   
379   380                              The Expendables 3   
410   411                                          Taken   
433   434           Mission: Impossible - Ghost Protocol   
444   445                                   The Thinning   
453   454                             Olympus Has Fallen   
560   561                                The Expendables   
580   581                           Kickboxer: Vengeance   
624   625                                        Taken 3   
698   699                          Live Free or Die Hard   
729   730                                      The Guest   
746   747                             Only for One Night   
770   771                              Quantum of Solace   
777   778                                     Final Girl   
844   845                                    Unstoppable   
848   849                                    Mean Dreams   
869   870                        Mission: Impossible III   
872   873                                       Red Dawn   
911   912  I Am the Pretty Thing That Lives in the House   
916   917                              The Expendables 2   
923   924                                      No Escape   
933   934                                         Detour   
942   943                                     Transpecos   
949   950                                          Kicks   

                         Genre  \
17             Action,Thriller   
123                     Action   
124            Action,Thriller   
164  Action,Adventure,Thriller   
169  Action,Adventure,Thriller   
233  Action,Adventure,Thriller   
270  Action,Adventure,Thriller   
282                   Thriller   
284           Action,Adventure   
289                   Thriller   
344           Action,Adventure   
368           Action,Adventure   
379  Action,Adventure,Thriller   
410            Action,Thriller   
433  Action,Adventure,Thriller   
444                   Thriller   
453            Action,Thriller   
560  Action,Adventure,Thriller   
580                     Action   
624            Action,Thriller   
698  Action,Adventure,Thriller   
729                   Thriller   
746                   Thriller   
770  Action,Adventure,Thriller   
777            Action,Thriller   
844            Action,Thriller   
848                   Thriller   
869  Action,Adventure,Thriller   
872            Action,Thriller   
911                   Thriller   
916  Action,Adventure,Thriller   
923            Action,Thriller   
933                   Thriller   
942                   Thriller   
949                  Adventure   

                                           Description               Director  \
17   The CIA's most dangerous former operative is d...        Paul Greengrass   
123  In the fourth installment of the fighting fran...        Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...      Christopher Nolan   
164  Armed with a licence to kill, Secret Agent Jam...        Martin Campbell   
169  A cryptic message from Bond's past sends him o...             Sam Mendes   
233  Ethan and team take on their most impossible m...  Christopher McQuarrie   
270  Bond's loyalty to M is tested when her past co.

In [233]:
df[df.Genre.str.lower().str.split(',').map(lambda x: 
                                           (len(x)<3) & 
                                           ('action' in x)&
                                           ((set(x) - set(['action','thriller','adventure']))==set()))]

Rank                   Title             Genre  \
17     18            Jason Bourne   Action,Thriller   
123   124    Boyka: Undisputed IV            Action   
124   125   The Dark Knight Rises   Action,Thriller   
284   285                Hercules  Action,Adventure   
344   345            Spider-Man 3  Action,Adventure   
368   369  The Amazing Spider-Man  Action,Adventure   
410   411                   Taken   Action,Thriller   
453   454      Olympus Has Fallen   Action,Thriller   
580   581    Kickboxer: Vengeance            Action   
624   625                 Taken 3   Action,Thriller   
777   778              Final Girl   Action,Thriller   
844   845             Unstoppable   Action,Thriller   
872   873                Red Dawn   Action,Thriller   
923   924               No Escape   Action,Thriller   

                                           Description           Director  \
17   The CIA's most dangerous former operative is d...    Paul Greengrass   
123  In the fourth installment of the fighting fran...    Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...  Christopher Nolan   
284  Having endured his legendary twelve labors, He...       Brett Ratner   
344  A strange black entity from another world bond...          Sam Raimi   
368  After Peter Parker is bitten by a genetically ...          Marc Webb   
410  A retired CIA agent travels across Europe and ...       Pierre Morel   
453  Disgraced Secret Service agent (and former pre...      Antoine Fuqua   
580         A kick boxer is out to avenge his brother.     John Stockwell   
624  Ex-government operative Bryan Mills is accused...    Olivier Megaton   
777  A man teaches a young woman how to become a co...      Tyler Shields   
844  With an unmanned, half-mile-long freight train...         Tony Scott   
872  A group of teenagers look to save their town f...        Dan Bradley   
923  In their new overseas home, an American family...  John Erick Dowdle   

                                                Actors  Year  \
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
123  Scott Adkins, Teodora Duhovnikova, Alon Aboutb...  2016   
124  Christian Bale, Tom Hardy, Anne Hathaway,Gary ...  2012   
284  Dwayne Johnson, John Hurt, Ian McShane, Joseph...  2014   
344  Tobey Maguire, Kirsten Dunst, Topher Grace, Th...  2007   
368  Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...  2012   
410  Liam Neeson, Maggie Grace, Famke Janssen, Lela...  2008   
453  Gerard Butler, Aaron Eckhart, Morgan Freeman,A...  2013   
580  Dave Bautista, Alain Moussi, Gina Carano, Jean...  2016   
624  Liam Neeson, Forest Whitaker, Maggie Grace,Fam...  2014   
777  Abigail Breslin, Wes Bentley, Logan Huffman,Al...  2015   
844  Denzel Washington, Chris Pine, Rosario Dawson,...  2010   
872  Chris Hemsworth, Isabel Lucas, Josh Hutcherson...  2012   
923  Lake Bell, Pierce Brosnan, Owen Wilson,Chatcha...  2015   

     Runtime (Minutes)  Rating    Votes  Revenue (Millions)  Metascore  
17                 123     6.7   150823              162.16       58.0  
123                 86     7.4    10428                 NaN        NaN  
124                164     8.5  1222645              448.13       78.0  
284                 98     6.0   122838               72.66       47.0  
344                139     6.2   406219              336.53       59.0  
368                136     7.0   474320              262.03       66.0  
410                 93     7.8   502961              145.00       50.0  
453                119     6.5   214994               98.90       41.0  
580                 90     4.9     6809              131.56       37.0  
624                109     6.0   144715               89.25       26.0  
777                 90     4.7     9026                 NaN       56.0  
844                 98     6.8   157499               81.56       69.0  
872                 93     5.4    64584               44.80       31.0  
923                103     6.8    57921 

## Applymap

1. Map works with Series only
2. Apply works with both Series and DataFrame
3. Applymap works onl with DataFrame


1. Map works with values in Series
2. Apply works with values in Serie and Series in DataFrame
3. Applymap works with values in DataFrame

Calculate the average number of words in description and name.

In every cell of 2 columns I need :
1. Get words
2. Count them

In [237]:
df_d=df[['Title','Description']]

In [240]:
df_d.Description.str.split().map(len).mean()

27.921

In [241]:
df_d.Title.str.split().map(len).mean()

2.605

In [245]:
df_d.applymap(lambda x: len(x.split())).mean()

Title           2.605
Description    27.921
dtype: float64

In [257]:
df_d[df_d.applymap(lambda x: 'super' in x.lower()).max(axis=1)]

Title  \
4                         Suicide Squad   
60   Batman v Superman: Dawn of Justice   
147                            Watchmen   
148                            Superbad   
179                             Ant-Man   
195  Captain America: The First Avenger   
205                      X: First Class   
219                            Kick-Ass   
222                          It Follows   
257      Rise of the Planet of the Apes   
278              Everybody Wants Some!!   
373                              Wanted   
400                             Minions   
438                          Kick-Ass 2   
497                             Super 8   
542                            Spectral   
562                            Sinister   
599                            Megamind   
603                     Kung Fu Panda 3   
638                          Unfriended   
675                            The Mist   
716                           Entourage   
737                        Body of Lies   
742              El secreto de sus ojos   
751                              Oculus   
773                   Lady in the Water   
778                         Chalk It Up   
787                           Max Steel   
789                             Hancock   
797                     Despicable Me 2   
818                           Annabelle   
918    Perfume: The Story of a Murderer   
924                    Superman Returns   
932                          The Ticket   
937                               Super   
995                Secret in Their Eyes   

                                           Description  
4    A secret government agency recruits some of th...  
60   Fearing that the actions of Superman are left ...  
147  In 1985 where former superheroes exist, the mu...  
148  Two co-dependent high school seniors are force...  
179  Armed with a super-suit with the astonishing a...  
195  Steve Rogers, a rejected military soldier tran...  
205  In 1962, the United States government enlists ...  
219  Dave Lizewski is an unnoticed high school stud...  
222  A young woman is followed by an unknown supern...  
257  A substance, designed to help the brain repair...  
278  In 1980, a group of college baseball players n...  
373  A frustrated office worker learns that he is t...  
400  Minions Stuart, Kevin and Bob are recruited by...  
438  Following Kick-Ass' heroics, other citizens ar...  
497  During the summer of 1979, a group of friends ...  
542  A sci-fi/thriller story centered on a special-...  
562  Washed-up true-crime writer Ellison Oswalt fin...  
599  The supervillain Megamind finally defeats his ...  
603  Continuing his "legendary adventures of awesom...  
638  A group of online chat room friends find thems...  
675  A freak storm unleashes a species of bloodthir...  
716  Movie star Vincent Chase, together with his bo...  
737  A CIA agent on the ground in Jordan hunts down...  
742  A retired legal counselor writes a novel hopin...  
751  A woman tries to exonerate her brother, who wa...  
773  Apartment building superintendent Cleveland He...  
778  When a super girly-girl is dumped by her boyfr...  
787  The adventures of teenager Max McGrath and his...  
789  Hancock is a superhero whose ill considered be...  
797  When Gru, the world's most super-bad turned su...  
818  A couple begins to experience terrifying super...  
918  Jean-Baptiste Grenouille, born with a superior...  
924  Superman reappears after a long absence, but i...  
932  A blind man who regains his vision finds himse...  
937  After his wife falls under the influence of a ...  
995  A tight-knit team of rising investigators, alo...